POST http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2020-01-01",
  "specialist": "Dr. Dre",
  "type": "Hospital",
  "description": "Patient complains of severe reproductive cough. Medications prescribed.",
  "diagnosisCodes": ["J06.9"],
  "discharge": {
    "date": "2020-01-14",
    "criteria": "Patient fully cured."
  }
}